"frontend: html":
  - changed-files:
      - any-glob-to-any-file: "**/*.html"

"frontend: css":
  - changed-files:
      - any-glob-to-any-file: "**/*.css"

"frontend: js":
  - changed-files:
      - any-glob-to-any-file: "**/*.js"

"assets":
  - changed-files:
      - any-glob-to-any-file: ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.svg", "**/*.webp"]

"ci/cd":
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"

"docs":
  - changed-files:
      - any-glob-to-any-file: ["**/*.md", "docs/**"]
